import { StyleSheet, Platform } from 'react-native';

export const fontStyle = Platform.OS === 'web'
  ? 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif'
  : undefined;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#F8FAFC', // Crisp light background from mockup
  },
  sidebar: {
    width: 240,
    backgroundColor: '#0F243E', // Navy Blue from mockup
    padding: 24,
    justifyContent: 'space-between',
  },
  sidebarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 40,
  },
  miniLogo: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: '#1D4ED8', // Active blue highlight
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  miniLogoText: {
    fontSize: 16,
    fontWeight: '900',
    color: '#FFFFFF',
    fontFamily: fontStyle,
  },
  sidebarTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
    fontFamily: fontStyle,
  },
  sidebarSubtitle: {
    fontSize: 10,
    color: '#94A3B8',
    fontFamily: fontStyle,
  },
  menuItems: {
    flex: 1,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginBottom: 6,
  },
  menuItemActive: {
    backgroundColor: '#1D4ED8', // Solid blue active selection from mockup
  },
  menuIcon: {
    fontSize: 14,
    marginRight: 16,
  },
  menuItemText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#94A3B8',
    letterSpacing: 0.5,
    fontFamily: fontStyle,
  },
  menuItemTextActive: {
    color: '#FFFFFF', // White text on active tab
  },
  adminFooterCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    padding: 12,
    borderRadius: 16,
  },
  adminAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#3B82F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontFamily: fontStyle,
  },
  adminInfo: {
    flex: 1,
    marginLeft: 10,
  },
  adminName: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
    fontFamily: fontStyle,
  },
  adminEmail: {
    fontSize: 9,
    color: '#94A3B8',
    fontFamily: fontStyle,
  },
  logoutMiniBtn: {
    padding: 4,
  },
  mainContent: {
    flex: 1,
    paddingHorizontal: 32,
    paddingVertical: 24,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0F172A',
    fontFamily: fontStyle,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerDateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginRight: 16,
  },
  headerDateText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0F172A',
    fontFamily: fontStyle,
  },
  headerProfileBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 30,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginLeft: 16,
  },
  alertCardCompact: {
    width: 200,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  alertIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingHorizontal: 12,
    width: 250,
    marginRight: 16,
  },
  searchIcon: {
    marginRight: 8,
    color: '#64748B',
  },
  headerSearchInput: {
    flex: 1,
    paddingVertical: 10,
    fontSize: 13,
    color: '#0F172A',
  },
  iconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    position: 'relative',
  },
  badgeAlertDot: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#FF3B30',
  },
  loadingWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollContainer: {
    flexGrow: 1,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -8,
    marginBottom: 20,
  },
  statCard: {
    flex: 1,
    minWidth: 210,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    paddingVertical: 24,
    paddingHorizontal: 26,
    marginHorizontal: 8,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.01,
    shadowRadius: 4,
  },
  statIconBg: {
    width: 56,
    height: 56,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748B',
  },
  statValue: {
    fontSize: 28,
    fontWeight: '800',
    color: '#0F172A',
    marginVertical: 2,
  },
  statTrendText: {
    fontSize: 11,
    color: '#64748B',
  },
  trackingChartRow: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  mapCard: {
    flex: 1.2,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 20,
    marginRight: 16,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 16,
    fontFamily: fontStyle,
  },
  mockMapContainer: {
    height: 220,
    backgroundColor: '#EFF6FF', // Light blue water/map body
    borderRadius: 12,
    position: 'relative',
    overflow: 'hidden',
  },
  mapBgLine1: {
    position: 'absolute',
    top: 50,
    left: -20,
    width: 400,
    height: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    transform: [{ rotate: '25deg' }],
  },
  mapBgLine2: {
    position: 'absolute',
    top: 130,
    left: -20,
    width: 400,
    height: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    transform: [{ rotate: '-15deg' }],
  },
  mapBgLine3: {
    position: 'absolute',
    top: 100,
    left: 80,
    width: 2,
    height: 200,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
  },
  mapPin: {
    position: 'absolute',
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#1D4ED8',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  mapPinPopup: {
    position: 'absolute',
    top: 50,
    left: 120,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    width: 150,
  },
  popupPlate: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 2,
    fontFamily: fontStyle,
  },
  popupSpeed: {
    fontSize: 9,
    fontWeight: '700',
    color: '#24D164',
    marginBottom: 4,
    fontFamily: fontStyle,
  },
  popupLoc: {
    fontSize: 10,
    color: '#64748B',
    marginBottom: 2,
    fontFamily: fontStyle,
  },
  popupTime: {
    fontSize: 8,
    color: '#94A3B8',
    fontFamily: fontStyle,
  },
  donutCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 20,
  },
  chartContentWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    height: 220,
  },
  donutCircle: {
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 12,
    borderColor: '#24D164', // Green running default ring
    justifyContent: 'center',
    alignItems: 'center',
  },
  donutInnerCircle: {
    width: 86,
    height: 86,
    borderRadius: 43,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  donutMiddleNum: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0F172A',
    fontFamily: fontStyle,
  },
  donutMiddleLabel: {
    fontSize: 10,
    color: '#64748B',
    fontFamily: fontStyle,
  },
  donutLegend: {
    justifyContent: 'center',
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  legendLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748B',
    width: 60,
    fontFamily: fontStyle,
  },
  legendVal: {
    fontSize: 11,
    fontWeight: '700',
    color: '#0F172A',
    fontFamily: fontStyle,
  },
  bottomStatCard: {
    flex: 1,
    minWidth: 160,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 8,
    marginBottom: 16,
  },
  bottomCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  bottomStatLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748B',
    marginBottom: 4,
  },
  bottomStatValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 12,
  },
  sparklineContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 35,
    marginBottom: 12,
  },
  sparkBar: {
    width: 6,
    backgroundColor: '#24D164',
    marginRight: 4,
    borderRadius: 2,
  },
  viewAllBtn: {
    alignSelf: 'flex-start',
  },
  viewAllText: {
    fontSize: 11,
    color: '#1D4ED8',
    fontWeight: '700',
  },
  rightVehiclesPanel: {
    width: 380,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 20,
    padding: 20,
  },
  panelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  panelTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
  },
  panelAddBtn: {
    backgroundColor: '#1D4ED8',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  panelAddBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  panelSearchRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  panelSearchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    paddingHorizontal: 10,
    marginRight: 8,
  },
  panelSearchInput: {
    flex: 1,
    paddingVertical: 8,
    fontSize: 12,
    color: '#0F172A',
  },
  panelFilterBtn: {
    width: 36,
    height: 36,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rightTableHeader: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: '#F1F5F9',
    paddingBottom: 8,
    marginBottom: 8,
  },
  rightColHead: {
    fontSize: 9,
    fontWeight: '700',
    color: '#94A3B8',
  },
  rightVehicleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: '#F8FAFC',
    paddingVertical: 12,
  },
  miniVehicleAvatar: {
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  vehiclePlateText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0F172A',
  },
  vehicleModelText: {
    fontSize: 9,
    color: '#94A3B8',
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 6,
  },
  vehicleStatusLabel: {
    fontSize: 11,
    color: '#475569',
    fontWeight: '500',
  },
  rowCell: {
    fontSize: 11,
  },
  emptyText: {
    color: '#94A3B8',
    textAlign: 'center',
    fontSize: 13,
    paddingVertical: 30,
  },
  paginationRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderColor: '#F1F5F9',
  },
  pageArrow: {
    padding: 6,
  },
  pageNumber: {
    width: 24,
    height: 24,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 4,
  },
  pageNumberActive: {
    backgroundColor: '#EFF6FF',
  },
  pageNumberText: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '600',
  },
  pageNumberTextActive: {
    fontSize: 11,
    color: '#1D4ED8',
    fontWeight: '700',
  },
  sectionCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: '#0F172A',
  },
  addButton: {
    backgroundColor: '#1D4ED8',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  addButtonText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  searchBar: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    color: '#0F172A',
    fontSize: 14,
    marginBottom: 20,
  },
  table: {
    width: '100%',
  },
  tableHeaderRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
    paddingBottom: 12,
    marginBottom: 12,
  },
  tableHeaderCell: {
    fontSize: 10,
    fontWeight: '900',
    color: '#64748B',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: '#F8FAFC',
    paddingVertical: 14,
    alignItems: 'center',
  },
  tableCell: {
    fontSize: 13,
    color: '#64748B',
  },
  tableCellActions: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  actionBtn: {
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginHorizontal: 4,
  },
  actionBtnText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  detailContainer: {
    marginTop: 32,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 24,
  },
  detailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
    paddingBottom: 16,
    marginBottom: 20,
  },
  detailTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0F172A',
  },
  detailBody: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 24,
  },
  detailItem: {
    flex: 1,
    minWidth: 200,
    marginBottom: 16,
  },
  detailLabel: {
    fontSize: 9,
    fontWeight: '900',
    color: '#64748B',
    marginBottom: 4,
  },
  detailValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
  },
  detailSectionTitle: {
    fontSize: 11,
    fontWeight: '900',
    color: '#64748B',
    marginTop: 16,
    marginBottom: 12,
  },
  filterRow: {
    flexDirection: 'row',
    marginBottom: 20,
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  filterLabel: {
    fontSize: 9,
    fontWeight: '900',
    color: '#64748B',
    marginBottom: 8,
  },
  filterInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    color: '#0F172A',
    fontSize: 13,
  },
  dateSelector: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  dateChip: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginRight: 8,
    marginBottom: 8,
  },
  dateChipActive: {
    backgroundColor: '#1D4ED8',
    borderColor: '#1D4ED8',
  },
  dateChipText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#64748B',
  },
  dateChipTextActive: {
    color: '#FFFFFF',
  },
  formContainer: {
    maxWidth: 500,
    marginTop: 20,
  },
  inputLabel: {
    fontSize: 9,
    fontWeight: '900',
    color: '#64748B',
    marginBottom: 8,
  },
  textInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    color: '#0F172A',
    fontSize: 14,
  },
  spacer: {
    height: 16,
  },
  statusText: {
    color: '#24D164',
    fontWeight: 'bold',
    fontSize: 13,
    marginTop: 16,
    textAlign: 'center',
  },
  saveBtn: {
    marginTop: 24,
    backgroundColor: '#1D4ED8',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  saveBtnText: {
    fontSize: 13,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCard: {
    width: '90%',
    maxWidth: 500,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 24,
    padding: 32,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0F172A',
    marginBottom: 24,
  },
  modalInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    color: '#0F172A',
    fontSize: 14,
    marginBottom: 16,
  },
  modalActionRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 24,
  },
  modalBtn: {
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginLeft: 12,
  },
  modalBtnText: {
    fontSize: 12,
    fontWeight: '900',
  },
  activityRow: {
    borderBottomWidth: 1,
    borderColor: '#F8FAFC',
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  activityLabelWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  activeDotLabel: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#24D164',
    marginRight: 10,
  },
  activityText: {
    fontSize: 13,
    color: '#64748B',
    flex: 1,
  },
  activityTime: {
    fontSize: 11,
    color: '#94A3B8',
    marginLeft: 12,
  },
});
